### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by icetrahan** [Kein/islestats#1]
Could you add me on Discord Icetrahan.

I've got some stuff i wanna ask you about, would really appreciate you time $

**Comment by Kein** [comment]
Ask here

**Comment by icetrahan** [comment]
I was wondering if you every got Dumper7 to work properly. We are trying to figure out how to change players colors in game and was hoping maybe you knew something about it

**Comment by icetrahan** [comment]
On evrima. Trying to get custom colors dev colors style.  We're going to need to inject the data somehow. Did u even figure out how to make dumper7 work for evrima.

**Comment by Kein** [comment]
The Dumper7 issues wasn't relevant to me, it was just a curiosity as to why it crashes, because there wasn't anything  specific that would cause that.
For the "colors" I have a full-fledged deployable solution. It is not free, but nothing egregious either.  You can contact me in the islecord.
